### ISSUE TITLE
ERROR Compiling cuberevo

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/meta-fulan#13]
Compiling cuberevo_mini image, please wait ...

Building image for cuberevo_mini
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
WARNING: /home/ghani/openvision/openpli-oe-core/openvision-oe/meta-fulan/recipes-bsp/extra/stlirc_0.9.0.bb: Unable to get checksum for stlirc SRC_URI entry lircd_cuberevo_mini.conf: file could not be found
ERROR: ExpansionError during parsing /home/ghani/openvision/openpli-oe-core/meta-openpli/recipes-support/lsdir/lsdir_git.bb
Traceback (most recent call last):
  File "/home/ghani/openvision/openpli-oe-core/bitbake/lib/bb/data_smart.py", line 412, in DataSmart.expandWithRefs(s='1.0+git${SRCPV}', varname='PV'):
                 try:
    >                s = __expand_var_regexp__.sub(varparse.var_sub, s)
                     try:
  File "/home/ghani/openvision/openpli-oe-core/bitbake/lib/bb/data_smart.py", line 111, in VariableParse.var_sub(match=<_sre.SRE_Match object; span=(7, 15), match='${SRCPV}'>):
                 else:
    >                var = self.d.getVarFlag(key, "_content")
                 self.references.add(key)
  File "/home/ghani/openvision/openpli-oe-core/bitbake/lib/bb/data_smart.py", line 794, in DataSmart.getVarFlag(var='SRCPV', flag='_content', expand=True, noweakdefault=False, parsing=False):
                     cachename = var + "[" + flag + "]"
    >            value = self.expand(value, cachename)
     
  File "/home/ghani/openvision/openpli-oe-core/bitbake/lib/bb/data_smart.py", line 436, in DataSmart.expand(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value
     
  File "/home/ghani/openvision/openpli-oe-core/bitbake/lib/bb/data_smart.py", line 426, in DataSmart.expandWithRefs(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-0F0LEMk6jz"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/ghani/openvision/openpli-oe-core/openembedded-core/scripts:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot-native/usr/bin/sh4-oe-linux:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot/usr/bin/crossscripts:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot-native/usr/sbin:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot-native/usr/bin:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot-native/sbin:/home/ghani/openvision/openpli-oe-core/build/tmp/work/sh4-oe-linux/lsdir/fetcheravoidrecurse-r0/recipe-sysroot-native/bin:/home/ghani/openvision/openpli-oe-core/bitbake/bin:/home/ghani/openvision/openpli-oe-core/build/tmp/hosttools"; export HOME="/home/ghani"; git -c core.fsyncobjectfiles=0 ls-remote git://github.com/samsamsam-iptvplayer/lsdir.git  failed with exit code 128, output:
fatal: remote error: 
  Repository not found.

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:125: die Regel für Ziel „image“ scheiterte
make: *** [image] Fehler 1

Done, the compiled image is in build/tmp/deploy/images/cuberevo_mini folder!
It's a zipped file like openvision-enigma2-develop-7.0-rx-cuberevo_mini.zip

---------- update ---------

fixed

**Comment by backup1977** [comment]
|   CC [M]  /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/simu_button/simu_button.o
| /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/stgfb/stmfb/Makefile:374: *** missing 'endif'.  Stop.
| /home/ghani/openvision/openpli-oe-core/build/tmp/work-shared/cuberevo_mini/kernel-source/scripts/Makefile.build:365: recipe for target '/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/stgfb/stmfb' failed
| make[3]: *** [/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/stgfb/stmfb] Error 2
| /home/ghani/openvision/openpli-oe-core/build/tmp/work-shared/cuberevo_mini/kernel-source/scripts/Makefile.build:365: recipe for target '/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/stgfb' failed
| make[2]: *** [/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git/stgfb] Error 2
| /home/ghani/openvision/openpli-oe-core/build/tmp/work-shared/cuberevo_mini/kernel-source/Makefile:1429: recipe for target '_module_/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git' failed
| make[1]: *** [_module_/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/git] Error 2
| make[1]: Leaving directory '/home/ghani/openvision/openpli-oe-core/build/tmp/work-shared/cuberevo_mini/kernel-build-artifacts'
| Makefile:120: recipe for target 'sub-make' failed
| make: *** [sub-make] Error 2
| make: Leaving directory '/home/ghani/openvision/openpli-oe-core/build/tmp/work-shared/cuberevo_mini/kernel-source'
| WARNING: /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/temp/run.do_compile.9282:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo_mini-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-cuberevo_mini-r0/temp/log.do_compile.9282)
ERROR: Task (/home/ghani/openvision/openpli-oe-core/openvision-oe/meta-fulan/recipes-bsp/drivers/fulan-dvb-modules.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5614 tasks of which 4223 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/ghani/openvision/openpli-oe-core/openvision-oe/meta-fulan/recipes-bsp/drivers/fulan-dvb-modules.bb:do_compile
Summary: There were 18 WARNING messages shown.
Summary: There were 18 ERROR messages shown, returning a non-zero exit code.
Makefile:125: die Regel für Ziel „image“ scheiterte
make: *** [image] Fehler 1

Done, the compiled image is in build/tmp/deploy/images/cuberevo_mini folder!
It's a zipped file like openvision-enigma2-develop-7.0-rx-cuberevo_mini.zip

**Comment by BarviX6** [comment]
spark
ERROR: Task (/home/barvix/openpli-oe-core/openvision-oe/meta-fulan/recipes-bsp/drivers/fulan-dvb-modules.bb:do_compile) failed with exit code '1'

/home/barvix/openpli-oe-core/build/tmp/work/spark-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-spark-r0/git/stgfb/stmfb/Makefile:374: *** missing 'endif'.  Stop.
/home/barvix/openpli-oe-core/build/tmp/work-shared/spark/kernel-source/scripts/Makefile.build:365: recipe for target '/home/barvix/openpli-oe-core/build/tmp/work/spark-oe-linux/fulan-dvb-modules/2.6.32.71-stm24-0217+gitAUTOINC+e347027234-spark-r0/git/stgfb/stmfb' failed
