### ISSUE TITLE
keyboard is not working  [cuberevo mini]

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/meta-fulan#14]
**Hello,
the keyboard does not work when typing, I can not write anything
it's not working
please fix**

![20190113_213413](https://user-images.githubusercontent.com/10188931/51090960-b2d17b00-177b-11e9-81dd-14b14ebdc8a6.jpg)
![20190113_213609](https://user-images.githubusercontent.com/10188931/51090961-b2d17b00-177b-11e9-9c26-09628e83ac95.jpg)

**also when pressing on TEXT for Virtual Keyboard does not work**

![20190113_214416](https://user-images.githubusercontent.com/10188931/51091006-528f0900-177c-11e9-8af2-696487135c7d.jpg)

**Comment by persianpros** [comment]
As we changed so many things you need to compile and test again.
