### ISSUE TITLE
cuberevo mini does not start at all now

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/meta-fulan#17]
now the cuberevo mini does not start at all, please delete this change 

https://github.com/OpenVisionE2/meta-fulan/commit/a16771c6b18f30793a1f5dcf005e726afe768571

and go back to it

https://github.com/OpenVisionE2/meta-fulan/commit/048f6f55bbf8194223b350927b6fe3beed5a1f0b#diff-2a2ab45919b5842e8ebb624eb627a9fb

**Comment by sid8796** [comment]
Please show the log ...

**Comment by persianpros** [comment]
Use https://github.com/OpenVisionE2/meta-fulan/issues/16
