### ISSUE TITLE
Help to compile for rare SH4 boxes

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/meta-fulan#20]
I just added the needed sources for:

cuberevo_9500hd
vip1_v2
vip2_v1

but I couldn't compile successfully and I need help to fix the errors ...

Update: pace7241 is ok now.

**Comment by persianpros** [comment]
I don't have any SH4 and there were only spark before, but I brought what you see today so it could help others :)

**Comment by Hains** [comment]
Maybe this evening?
I'm leaving soon.

**Comment by persianpros** [comment]
That's great, I could work with my linux tomorrow
