### ISSUE TITLE
Need Image For Octagon1008

### ISSUE THREAD

**Issue by ahmedamour** [OpenVisionE2/meta-fulan#7]
Hi
I need both usb and tar image for octagon1008

**Comment by kueken** [comment]
Image is too big for internal memory of the box

**Comment by Hains** [comment]
@kueken 
Update and try again.
https://github.com/OpenVisionE2/meta-fulan/commit/19da3470cfc3772f258517fda1990130ab8defa1

**Comment by kueken** [comment]
was meant as info for the commit about it ;-

**Comment by persianpros** [comment]
We don't even know how to pack the image for these kind of models ...

**Comment by kueken** [comment]
You mean to pack?
Or do you mean flashing?

Duckba USB-Tool makes sh4 Boxes ready for all Images.
Spark/spark7162 enough memory internally.
I would say all others need installation of USB stick.
But then you need the 'tar.image' and the boxes run from USB stick.
That should be fast enough, too.
greetings

**Comment by ahmedamour** [comment]
Can you compile it for me.
