### ISSUE TITLE
Boot Probleme mit alle cuberevo's

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/meta-fulan#8]
Hallo
Ich habe verschiedene image gebaut für die cuberevo_mini, und cuberevo_250hd als tar.gz und getestet, aber box hängt sich sofort beim starten im display auf SH4, und geht nicht weiter, weil andere module, oder treibern werden nicht geladen!
Ich glaube das problem ist am treiber, oder im etc/init.d/ddbootup 
da, die einstellungen vieleicht, nur für spark ist.

**Comment by persianpros** [comment]
Who said we have German support?
Use English so everybody could understand it and BTW only spark is ok in SH4 as we don't know how to fix others.
